import type { Metadata } from 'next';
import '../globals.css';
import Header from '../components/Header';
import localFont from 'next/font/local';

const nanumSquare = localFont({
  src: [
    {
      path: '../fonts/NanumSquareR.ttf',
      weight: '400',
    },
    {
      path: '../fonts/NanumSquareB.ttf',
      weight: '700',
    },
  ],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='ko' className={`${nanumSquare.className} h-full antialiased`}>
      <body className='min-h-full flex flex-col'>
        <Header />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
