import type { Metadata } from 'next';
import '../globals.css';
import Header from '../components/common/Header';
import localFont from 'next/font/local';
import QueryProvider from '../components/QueryProvider';

const nanumSquare = localFont({
  src: [
    {
      path: '../fonts/NanumSquareR.ttf',
      weight: '400',
    },
    {
      path: '../fonts/NanumSquareB.ttf',
      weight: '700',
    },
  ],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='ko' className={`${nanumSquare.className} h-full antialiased`}>
      <body className='min-h-full flex flex-col'>
        <QueryProvider>
          <Header />
          <div className='text-slate-800 px-[16px] sm:px-[24px] lg:px-[360px]'>
            {children}
          </div>
        </QueryProvider>
      </body>
    </html>
  );
};

export default RootLayout;
